// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTag.Helpers;

namespace UTag.Migrations
{
    [DbContext(typeof(UTagContext))]
    partial class UTagContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UTag.Models.Filter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dimension");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("UTag.Models.FilterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilterId");

                    b.Property<int>("ProductId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("FilterId");

                    b.HasIndex("ProductId");

                    b.ToTable("FilterValues");
                });

            modelBuilder.Entity("UTag.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About");

                    b.Property<DateTime>("BirthDate");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("UTag.Models.PersonConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendStatus");

                    b.Property<int>("FromPersonId");

                    b.Property<bool>("PersonToExists");

                    b.Property<int>("ToPersonId");

                    b.HasKey("Id");

                    b.HasIndex("FromPersonId");

                    b.HasIndex("ToPersonId");

                    b.ToTable("PersonConnection");
                });

            modelBuilder.Entity("UTag.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About");

                    b.Property<string>("ImageBase64");

                    b.Property<string>("Link");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("UTag.Models.ProductConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PersonFromId");

                    b.Property<int>("PersonToId");

                    b.Property<int>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("PersonFromId");

                    b.HasIndex("PersonToId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductConnection");
                });

            modelBuilder.Entity("UTag.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("UTag.Models.TagConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConnectToId");

                    b.Property<int>("ConnectToType");

                    b.Property<int?>("PersonId");

                    b.Property<int>("TagId");

                    b.HasKey("Id");

                    b.HasIndex("ConnectToId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TagId");

                    b.ToTable("TagConnections");
                });

            modelBuilder.Entity("UTag.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UTag.Models.FilterValue", b =>
                {
                    b.HasOne("UTag.Models.Filter", "Filter")
                        .WithMany("FilterValues")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UTag.Models.Product", "Product")
                        .WithMany("FilterValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UTag.Models.Person", b =>
                {
                    b.HasOne("UTag.Models.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("UTag.Models.Person", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UTag.Models.PersonConnection", b =>
                {
                    b.HasOne("UTag.Models.Person", "FromPerson")
                        .WithMany("ConnectedPersons")
                        .HasForeignKey("FromPersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UTag.Models.Person", "ToPerson")
                        .WithMany()
                        .HasForeignKey("ToPersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UTag.Models.ProductConnection", b =>
                {
                    b.HasOne("UTag.Models.Person", "PersonFrom")
                        .WithMany("LikedProducts")
                        .HasForeignKey("PersonFromId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UTag.Models.Person", "PersonTo")
                        .WithMany("LikedForPersonProducts")
                        .HasForeignKey("PersonToId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UTag.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UTag.Models.TagConnection", b =>
                {
                    b.HasOne("UTag.Models.Product", "ConnectedTo")
                        .WithMany("ConnectedTags")
                        .HasForeignKey("ConnectToId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UTag.Models.Person")
                        .WithMany("ConnectedTags")
                        .HasForeignKey("PersonId");

                    b.HasOne("UTag.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
